import fs from "node:fs"
import fsp from "node:fs/promises"
import path from "node:path"
import { NextResponse } from "next/server"
import type { ReadableStream as WebReadableStream } from "node:stream/web"
import { Readable } from "node:stream"

import { sqlite } from "@/db"
import { getSession } from "@/lib/session"
import { UPLOADS_DIR } from "@/lib/paths"

const CONTENT_TYPES: Record<string, string> = {
  ".epub": "application/epub+zip",
  ".pdf": "application/pdf",
  ".mobi": "application/x-mobipocket-ebook",
  ".azw3": "application/vnd.amazon.ebook",
  ".cbz": "application/vnd.comicbook+zip",
}

/**
 * Ebook downloads go through here rather than being served statically, so the
 * session is always checked first. Uploaded files live outside the public tree.
 */
export async function GET(
  _request: Request,
  { params }: { params: Promise<{ copyId: string }> }
) {
  if (!(await getSession())) {
    return new NextResponse("Unauthorized", { status: 401 })
  }

  const { copyId } = await params
  const id = Number(copyId)
  if (!Number.isInteger(id) || id <= 0) {
    return new NextResponse("Not found", { status: 404 })
  }

  const copy = sqlite
    .prepare("SELECT file_name AS fileName, file_path AS filePath FROM copies WHERE id = ?")
    .get(id) as { fileName: string | null; filePath: string | null } | undefined

  if (!copy?.filePath) return new NextResponse("Not found", { status: 404 })

  const absolute = path.resolve(UPLOADS_DIR, copy.filePath)
  // Belt and braces: the stored path is generated by us, but a corrupted row
  // must still not be able to read outside the uploads tree.
  if (!absolute.startsWith(UPLOADS_DIR + path.sep)) {
    return new NextResponse("Not found", { status: 404 })
  }

  let size: number
  try {
    size = (await fsp.stat(absolute)).size
  } catch {
    return new NextResponse("Not found", { status: 404 })
  }

  const fileName = copy.fileName ?? path.basename(absolute)
  const contentType =
    CONTENT_TYPES[path.extname(absolute).toLowerCase()] ?? "application/octet-stream"

  // Streamed, so a 100 MB file never sits in memory.
  const stream = Readable.toWeb(
    fs.createReadStream(absolute)
  ) as WebReadableStream<Uint8Array>

  return new NextResponse(stream as unknown as BodyInit, {
    headers: {
      "Content-Type": contentType,
      "Content-Length": String(size),
      "Content-Disposition": `attachment; filename="${encodeURIComponent(fileName)}"`,
      "Cache-Control": "private, no-store",
    },
  })
}
